@PlatformService_HostAddress = http://localhost:5161

GET {{PlatformService_HostAddress}}/api/Platforms/
Accept: application/json

###

GET {{PlatformService_HostAddress}}/api/Platforms/3
Accept: application/json

###

POST {{PlatformService_HostAddress}}/api/Platforms/
Content-Type: application/json

{
  "Name": "name",
  "Publisher": "publisher",
  "Cost": "cost"
}

### For docker

@AddressForDocker = http://localhost:80

GET {{AddressForDocker}}/api/Platforms/
Accept: application/json

###

GET {{AddressForDocker}}/api/Platforms/4
Accept: application/json

###

POST {{AddressForDocker}}/api/Platforms/
Content-Type: application/json

{
  "Name": "name",
  "Publisher": "publisher",
  "Cost": "cost"
}